// react/src/reception/checksin-log.tsx
import {CheckinLog} from '../models/checkinlog.model';
import {Component} from 'react';
import React from 'react';
import './checksin-log.css';

export interface ChecksinLogProps {
    checksinLog: Array<CheckinLog>;
}

export class ChecksinLog extends Component<ChecksinLogProps> {
    render() {
        return (
            <div className="reception-log">
                <h3>Log</h3>
                <div className="reception-log-container">
                    <table>
                        <thead className="reception-log-header">
                        <tr>
                            <th>Date</th>
                            <th>Event</th>
                        </tr>
                        </thead>
                        <tbody>
                        {this.props.checksinLog.map(this.RenderCheckinLogItem)}
                        </tbody>
                    </table>
                </div>
            </div>);
    };

    RenderCheckinLogItem(checkinLog: CheckinLog): JSX.Element {
        return (<tr>
            <td>{checkinLog.date.toLocaleDateString()} {checkinLog.date.toLocaleTimeString()}</td>
            <td>{checkinLog.message}</td>
        </tr>);
    }
}

// vue/src/components/ChecksinLog.vue
<template>
    <div class="reception-log">
        <h3>Log</h3>
        <table>
            <thead class="reception-log-header">
            <tr>
                <th>Date</th>
                <th>Event</th>
            </tr>
            </thead>
            <tbody>
            <tr v-for="(val) in checksinLog" :key="val.id">
                <td>{{val.date | formatDate}}</td>
                <td>{{val.message}}</td>
            </tr>
            </tbody>
        </table>
    </div>
</template>

<script lang="ts">
    import {Component, Prop, Vue} from 'vue-property-decorator';
    import {CheckinlogModel} from '@/models/checkinlog.model';

    @Component
    export default class ChecksinLog extends Vue {
        @Prop()
        public checksinLog!: CheckinlogModel[];
    }
</script>

<style lang="scss">
    .reception-log {
        text-align: center;
        width: 100%;

        table {
            min-width: 600px;
            margin: auto;
        }
    }
</style>
