// angular/base_example/src/app/reception/guest-list/guest-list.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {Checkin} from '../shared/checkin.model';
import {ReceptionService} from '../shared/reception.service';

@Component({
  selector: 'app-guest-list',
  templateUrl: './guest-list.component.html',
  styleUrls: ['./guest-list.component.scss']
})
export class GuestListComponent implements OnInit {

  constructor(private receptionService: ReceptionService) { }

  @Input()
  public checksin: Array<Checkin>;

  @Output()
  public checkout: EventEmitter<void> = new EventEmitter<void>();

  ngOnInit() {
  }

  public checkoutPerson(checkinId: number) {
    this.receptionService.checkout(checkinId).subscribe(() => this.checkout.emit());
  }
}

<div class="reception-guest-list">
  <h3>Guest list</h3>
  <div class="reception-guest-list-container">
    <table>
      <thead class="reception-guest-list-header">
        <tr>
          <th>Room</th>
          <th>Person</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let checkin of checksin">
          <td>{{checkin.room.name}}</td>
          <td>{{checkin.person.name}}</td>
          <td><a href="javascript:void(0)" (click)="checkoutPerson(checkin.id)">checkout</a></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// vue/src/components/GuestList.vue
<template>
    <div class="reception-guest-list">
        <h3>Guest list</h3>
        <div class="reception-guest-list-container">
            <table>
                <thead class="reception-guest-list-header">
                <tr>
                    <th>Room</th>
                    <th>Person</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="(val) in checksin" :key="val.id">
                    <td>{{val.room.name}}</td>
                    <td>{{val.person.name}}</td>
                    <td><a href="javascript:void(0)" v-on:click="checkout(val.id)">checkout</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script lang="ts">
    import {Component, Emit, Prop, Vue} from 'vue-property-decorator';
    import {CheckinModel} from '@/models/checkin.model';
    import {apiCheckout} from '@/libs/receptionApi.lib';

    @Component
    export default class GuestList extends Vue {

        @Prop()
        public checksin!: CheckinModel[];

        @Emit('onCheckout')
        public onCheckout() {
            return;
        }

        public checkout(id: number) {
            apiCheckout(id).then(() => this.onCheckout());
        }
    }
</script>

<style lang="scss">
    .reception-guest-list {
        text-align: center;
        width: 100%;

        table {
            min-width: 400px;
            margin: auto;
        }
    }
</style>
